Grasp especialista
UnBArqDsw2022-1/2022.1_G1_fgAvisos pull request #77
Opened 2022-08-08 14:17 UTC by vitordiniz25

Documento GRASP Especialista.

2022-08-08 14:24 UTC, victorhugo21 approved these changes
Muito bem explicado e exemplificado, excelente trabalho!!

2022-08-08 15:00 UTC, JoaoP-Coelho commented
Ótima explicação e bons exemplos utilizados, perfeito!

2022-08-08 15:01 UTC, JoaoP-Coelho reviewed
Ótima explicação e bons exemplos utilizados, perfeito!

2022-08-08 15:03 UTC, JoaoP-Coelho approved these changes

2022-08-08 15:23 UTC, LamequeFernandes requested changes
Muito bom, gostei da explicação, mas acredito que seria melhor se a figura 1 apresentasse apenas as classes que são referenciadas no tópico sobre a Aplicação no projeto, para melhor identificação da especialização citada.

2022-08-08 15:34 UTC, deivid-a1 requested changes
Como dito pelo @LamequeFernandes, acredito que agregaria mais utilizar nossa caso apenas com as classes que interessam, no caso a classe Usuário, Aluno, Professor e Aviso. O link para o diagrama é https://lucid.app/lucidchart/8646d955-d9d6-4ae4-97d8-f5ad43b69390/edit?viewport_loc=-2%2C-21%2C2525%2C1259%2CHWEp-vi-RSFO&invitationId=inv_4e00820c-0114-4bd6-833a-9cde0f9d449d#

2022-08-08 15:35 UTC, deivid-a1 commented
O repositório é privado? Tem problema deixar esse link aqui?

2022-08-08 16:33 UTC, LamequeFernandes commented
> O repositório é privado? Tem problema deixar esse link aqui?

tem problema não, mano

2022-08-08 18:23 UTC, hugorochaffs approved these changes
Perfeito!

2022-08-08 22:09 UTC, AntonioIgorCarvalho approved these changes
LGTM

2022-08-08 23:48 UTC, LamequeFernandes approved these changes

2022-08-08 23:50 UTC, LamequeFernandes approved these changes

2022-08-09 00:58 UTC, DaviMarinho approved these changes
LGTM!

2022-08-10 00:28 UTC, deivid-a1 approved these changes

2022-08-10 00:28 UTC, deivid-a1 commented
Fino!

2022-08-10 00:28 UTC, merged