Gof builder
UnBArqDsw2022-1/2022.1_G1_fgAvisos pull request #80
Opened 2022-08-09 15:08 UTC by mateus-lm

2022-08-09 15:28 UTC, JoaoP-Coelho requested changes
Ótimos exemplos utilizados, só esqueceram de retirar as frases do template no tópico Resultados

2022-08-09 15:42 UTC, JoaoP-Coelho approved these changes
Agora está perfeito!

2022-08-10 00:26 UTC, hugorochaffs approved these changes
Perfeito

2022-08-10 01:57 UTC, vitordiniz25 approved these changes
Muito bom! Didático e direto.
LGTM!

2022-08-10 03:15 UTC, merged